/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2c3134",
        "surface-bright": "#f6fafe",
        "surface": "#f6fafe",
        "secondary-container": "#c7dffd",
        "on-tertiary-container": "#5fa98c",
        "tertiary-fixed-dim": "#8bd6b6",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface": "#171c1f",
        "on-secondary-container": "#4c637d",
        "on-background": "#171c1f",
        "outline-variant": "#c3c6d1",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#324861",
        "secondary-fixed": "#d0e4ff",
        "surface-container-highest": "#dfe3e7",
        "on-primary-container": "#869ebc",
        "primary-fixed": "#d1e4ff",
        "outline": "#737780",
        "error": "#ba1a1a",
        "tertiary": "#002318",
        "secondary-fixed-dim": "#b1c9e6",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b0c9e8",
        "on-tertiary-fixed-variant": "#00513b",
        "primary": "#031f38",
        "on-primary-fixed-variant": "#314863",
        "secondary": "#4a607a",
        "on-primary-fixed": "#011d35",
        "background": "#f6fafe",
        "surface-variant": "#dfe3e7",
        "surface-dim": "#d6dade",
        "primary-container": "#1c354e",
        "on-tertiary-fixed": "#002116",
        "on-secondary-fixed": "#021d33",
        "surface-container": "#eaeef2",
        "inverse-primary": "#b0c9e8",
        "tertiary-fixed": "#a6f2d1",
        "on-surface-variant": "#43474f",
        "inverse-on-surface": "#edf1f5",
        "tertiary-container": "#003b2a",
        "surface-container-high": "#e4e9ed",
        "surface-tint": "#49607c",
        "surface-container-low": "#f0f4f8",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
